### ISSUE TITLE
Can't get the image - e2e-controller

### ISSUE THREAD

**Issue by prague34** [terragraph/tgnms#13]
Hello,

How can i get this image ? I'm getting an error on this image when trying to complete the installation with pex

manifest unknown
The following images are missing:
    ghcr.io/terragraph/e2e-controller:latest

Thanks

**Comment by aclave1** [comment]
The image is not currently publicly available. If you have an OEM controller image, you can change the installer to point to the registry which contains that image. via the config.yml file. If you don't have an OEM controller, you'll have to wait until the controller's source-code is open-sourced which should be soon!
